---
title: "Liner Testing Stats Visualization"
output:
  html_document:
    df_print: paged
    code_folding: show
  pdf_document: default
---


```{r setup}
# Import packages
library(tidyverse)
library(knitr)
library(bit)
library(scales)
library(ggeasy)

# Suppress warnings
opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

# Round values in tables to 2 digits
#kable <- function(data, caption = "") {
#  knitr::kable(data, digits = 2, caption = caption)
#}

# Function to read date from Excel
date_from_char <- function(char_date) {
  date <- as.Date(char_date, "%m/%d/%Y")
}

# Function to read percent from Excel
prop_from_percent <- function(char_percent) {
  prop <- as.numeric(gsub("%", "", char_percent))/100
}
```



```{r prep}


# Read file and select relevant data
systems <- read_csv("Liner Test Tracking & Projections.csv", col_names = TRUE, skip = 5) %>%
  select(sys_id = 3, contractor = 15, sys_depth = 17, sys_area = 18, 
         date_1 = 21, depth_1 = 25, filled_1 = 23, rr_1 = 24,
         date_2 = 27, depth_2 = 28, filled_2 = 29, rr_2 = 30,
         date_3 = 33, depth_3 = 34, filled_3 = 35, rr_3 = 36,
         date_4 = 39, depth_4 = 40, filled_4 = 41, rr_4 = 42,
         date_5 = 45, depth_5 = 46, filled_5 = 47, rr_5 = 48,
         date_6 = 51, depth_6 = 52, filled_6 = 53, rr_6 = 54,
         date_7 = 57, depth_7 = 58, filled_7 = 59, rr_7 = 60,
         date_8 = 63, depth_8 = 64, filled_8 = 65, rr_8 = 66,
         date_9 = 69, depth_9 = 70, filled_9 = 71, rr_9 = 72,
         status = 75, tests_to_pass = 76)

# Remove systems that haven't been tested
systems <- systems %>%
  filter(date_1 != "") 

# Clean up data and change types as needed
systems <- systems %>% 
  mutate(across(contains("date"), date_from_char)) %>%
  mutate(across(contains("filled"), prop_from_percent)) %>%
  mutate(
    contractor = toupper(contractor),
    sys_depth = as.numeric(sys_depth),
    sys_area = as.numeric(gsub(",", "", sys_area)),
    first_test_date = date_1,
    tests_to_pass = as.numeric(tests_to_pass),
    tests_to_pass_factor = factor(tests_to_pass, levels = seq(1, max(tests_to_pass, na.rm=TRUE))),
    first_test_fy = ifelse(month(first_test_date)>6, year(first_test_date)+1, year(first_test_date)),
    last_test_date = pmax(date_1, date_2, date_3, date_4, date_5, date_6, date_7, date_8, date_9, na.rm = TRUE)
  )

# Create tests dataframe with one row per test and remove rows without test data
tests <- pivot_longer(systems,
  cols = 5:40,
  names_to = c(".value","test_num"),
  names_sep = "_",) %>% 
  select(-tests_to_pass, -first_test_date) %>%
  filter(!is.na(date))

# Remove "status" col and add "result" col indicating whether test passed. Add FY 
tests <- tests %>%
  group_by(sys_id) %>%
    mutate(
      result = lag(status, n=length(status)-1, default="Fail"),
      FY = ifelse(month(date)>6, year(date)+1, year(date))) %>%
    select(-status)

# Remove test data from systems dataframe
systems <- systems %>%
  select(-contains("date_")) %>%
  select(-contains("depth_")) %>%
  select(-contains("filled_")) %>%
  select(-contains("rr_")) %>%
  relocate(first_test_date, .after = sys_id) %>%
  relocate(last_test_date, .after = first_test_date)  

```


```{r tests_by_year}
kable(
  tests %>%
    group_by(FY) %>%
    summarize(num_tests = n(), num_sys = n_distinct(sys_id)),
  col.names = c("Fiscal Year", "Number of Tests", "Number of Systems"),
  caption = "Liner Performance Tests by Fiscal Year"
)
```


```{r tests_by_year_chart}
tests_by_year_df <-   
  tests %>%
    group_by(FY) %>%
    summarize("No. of Tests" = n(), "No. of Systems" = n_distinct(sys_id)) %>%
    gather("Stat", "Value", -FY)


ggplot(tests_by_year_df, aes(x = FY, y = Value, fill = Stat)) + 
  geom_col(position = "dodge") + 
  geom_text(aes(x=FY, Value, label = Value),
            vjust = -.5, color = "black", position = position_dodge(0.9)) + 
  scale_y_continuous(breaks = seq(from = 0, to = 150, by = 25), minor_breaks = 25, limits = c(0,150)) +
  scale_x_discrete(limits = seq(min(year(tests$date)), max(year(tests$date)))) + 
  labs(title = "Liner Performance Tests by Fiscal Year", x = "Fiscal Year", y = "", fill = "") + 
  ggeasy::easy_center_title() + 
  theme(text = element_text(size= 14), legend.position = "bottom") 

```


```{r tests_to_pass}

all_sys_passed <- filter(systems, !is.na(tests_to_pass)) %>%
  group_by(num_tests = tests_to_pass_factor, .drop = FALSE) %>%
  summarize(
    num_sys = n(), 
    frac_total = n()/nrow(.)
  )
kable(
  all_sys_passed %>%
  mutate(percent_total = percent(frac_total, accuracy = 0.1)) %>%
  select(-frac_total), 
  col.names = c("Number of Tests", "Number of Systems", "Percentage of Total"), 
  caption = "Number of Tests to Pass: All Years"
)
 
#FY23 Only
sys_fy23_passed <- filter(systems, !is.na(tests_to_pass_factor) & first_test_fy == 2023) %>%
  group_by(num_tests = tests_to_pass_factor, .drop = FALSE) %>%
  summarize(
    num_sys = n(), 
    frac_total = n()/nrow(.)
  )
kable(
  sys_fy23_passed %>%
  mutate(percent_total = percent(frac_total, accuracy = 0.1)) %>%
  select(-frac_total), 
  col.names = c("Number of Tests", "Number of Systems", "Percentage of Total"), 
  caption = "Number of Tests to Pass: FY23 Only"
)

#FY24 Only
sys_fy24_passed <- filter(systems, !is.na(tests_to_pass_factor) & first_test_fy == 2024) %>%
  group_by(num_tests = tests_to_pass_factor, .drop = FALSE) %>%
  summarize(
    num_sys = n(), 
    frac_total = n()/nrow(.)
  )
kable(
  sys_fy24_passed %>%
  mutate(percent_total = percent(frac_total, accuracy = 0.1)) %>%
  select(-frac_total), 
  col.names = c("Number of Tests", "Number of Systems", "Percentage of Total"), 
  caption = "Number of Tests to Pass: FY24 Only"
)

#FY25 Only
sys_fy25_passed <- filter(systems, !is.na(tests_to_pass_factor) & first_test_fy == 2025) %>%
  group_by(num_tests = tests_to_pass_factor, .drop = FALSE) %>%
  summarize(
    num_sys = n(), 
    frac_total = n()/nrow(.)
  )
kable(
  sys_fy25_passed %>%
  mutate(percent_total = percent(frac_total, accuracy = 0.1)) %>%
  select(-frac_total), 
  col.names = c("Number of Tests", "Number of Systems", "Percentage of Total"), 
  caption = "Number of Tests to Pass: FY25 Only"
)
  

```

```{r tests_to_pass_bar_chart}

# All tests
ggplot(all_sys_passed, aes(x = num_tests, y = frac_total)) +
  geom_bar(stat = "identity", fill = "blue") + 
  geom_text(aes(label = percent(frac_total, accuracy = 0.1), vjust = -0.5, size = 3)) + 
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), limits = c(0, 1)) + 
  labs(title = "Tests Required to Pass: All Years", x = "Number of Tests", y = "% of Systems") + 
  ggeasy::easy_center_title() + 
  theme(legend.position = "none")

all_sys_passed_fy23_through_fy25 <- rbind(
  mutate(sys_fy23_passed, fy=2023),
  mutate(sys_fy24_passed, fy=2024),
  mutate(sys_fy25_passed, fy=2025)
)

ggplot(all_sys_passed_fy23_through_fy25, aes(x = num_tests, y = frac_total)) +
  geom_bar(stat = "identity", fill = "blue") + 
  facet_wrap(~fy, ncol = 1) + 
  geom_text(aes(label = percent(frac_total, accuracy = 0.1), vjust = -0.5, size = 3)) + 
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), limits = c(0, 1)) + 
  labs(title = "Tests Required to Pass: 2023 - 2025", x = "Number of Tests", y = "% of Systems") + 
  ggeasy::easy_center_title() + 
  theme(legend.position = "none")


```

```{r avg_tests_to_pass_by_year}
kable(
  filter(systems, !is.na((tests_to_pass))) %>%
  group_by(first_test_fy) %>%
  summarize(num_sys = n(), 
            avg_tests_to_pass = mean(tests_to_pass)),
  digits = 2,
  caption = "Average Number of Tests to Pass by Fiscal Year",
  col.names = c("Fiscal Year of First Test", "Number of Systems Passed", "Average Number of Tests to Pass")
)
```

```{r tests_to_pass_by_contractor}
kable(
  filter(systems, !is.na((tests_to_pass))) %>%
  group_by(contractor) %>%
  summarize(num_sys = n(), 
            avg_tests_to_pass = mean(tests_to_pass)) %>%
  arrange(select(., 3)),
  digits = 2,
  caption = "Average Number of Tests to Pass by Contractor",
  col.names = c("Contractor", "Number of Systems Passed", "Average Number of Tests to Pass")
)
```

```{r med_rr_by_fy}
kable(
  tests %>%
    group_by(FY) %>%
    summarize(med_rr = median(rr, na.rm = TRUE)),
  digits = 2,
  caption = "Median of Max Recession Rate by Fiscal Year", 
  col.names = c("Fiscal Year", "Median of Max Recession Rate")
)

```

```{r max_rr_ts}
fy_starts <- seq(from = date_from_char("7/1/2020"), by = "year", length.out = 5)
ggplot(data = tests, mapping = aes(x = date, y = rr, color = result)) + 
  geom_point() + 
  scale_y_continuous(breaks = seq(from = 0, to = 16, by = 2), limits = c(0, 16)) +
  stat_smooth(method = "lm", formula = y~x, se=FALSE, linetype = "dashed", color = "black") + 
  annotate("text", x = date_from_char("5/1/2020"), y = 4.4, label = "Linear Fit", angle = -4) + 
  geom_hline(yintercept = 1, linetype = "dashed") + 
  annotate("text", x = date_from_char("2/15/2020"), y = 0.6, label = "1 in/hr Limit") + 
  scale_x_date(breaks = fy_starts,
               date_minor_breaks = "3 months",
               limits = c(date_from_char("1/1/2020"), date_from_char("4/1/2025"))
  ) +
  labs(title = "Timeseries of Max Recession Rates", x = "Date", y = "Maximum Recession Rate (in/hr)") + 
  theme(legend.position = "bottom", plot.title = element_text(size = 12), legend.title=element_blank()) + 
  ggeasy::easy_center_title()
```


```{r percent_filed_ts}

ggplot(data = tests, mapping = aes(x = date, y = filled, color = result)) + 
  geom_point() + 
  scale_y_continuous(breaks = seq(0, 1.5, by=0.25), limits = c(0,max(max(tests$filled), 1.5)), 
                     labels = percent) +
  stat_smooth(method = "lm", formula = y~x, se=FALSE, linetype = "dashed", color = "black") + 
  annotate("text", x = date_from_char("2/15/2021"), y = 0.835, label = "Linear Fit", angle = 3) + 
  geom_hline(yintercept = 1, linetype = "dashed") + 
  annotate("text", x = date_from_char("5/1/2020"), y = 1.06, label = "1 in/hr Limit") + 
  scale_x_date(breaks = fy_starts,
               date_minor_breaks = "3 months",
               limits = c(date_from_char("1/1/2020"), date_from_char("4/1/2025"))
  ) +
  labs(title = "Timeseries of Percent Storage Depth Filled", x = "Date", y = "Percent Filled") + 
  theme(legend.position = "bottom", plot.title = element_text(size = 12), legend.title=element_blank()) + 
  ggeasy::easy_center_title()
```

```{r passes_with_low_rr}
# Calculate the number and percent of systems first tested in FY25 that would meet the 0.5 in/hr limit
n_pass_FY25 <- nrow(filter(tests, FY == 2025 & result == "Pass"))
n_pass_FY25_low_rr <- nrow(filter(tests, FY == 2025 & result == "Pass" & rr < 0.5))
print(paste0("Total Passes in FY25 so far: ", n_pass_FY25))
print(paste0("Passes in FY25 with max recession rate below 0.5 in/hr: ", n_pass_FY25_low_rr))
print(paste0("Percent of FY25 passes with max rr below 0.5 in/hr: ", percent(n_pass_FY25_low_rr/n_pass_FY25, accuracy = 2)))

```
